### ISSUE TITLE
Maybe put some screenshots in the readme... :)

### ISSUE THREAD

**Issue by pouyakary** [deermichel/soundboard#1]
I'm curious ...

**Comment by deermichel** [comment]
Haha, yeah, writing a README in general is definitely one of my next todos 💯

**Comment by pouyakary** [comment]
:)))))) goood

**Comment by deermichel** [comment]
Yay, [here](https://github.com/deermichel/soundboard/blob/f5a19cf00c80cf9942523ed157f744a5961fe9f3/README.md) you go - so I can close my first issue now 🥳

**Comment by deermichel** [comment]
ah wait let me add a screenshot :)
